### ISSUE TITLE
Timeline?

### ISSUE THREAD

**Issue by Natelegreat1** [blinkinput/blinkinput-xamarin#1]
Hello.
Any timeline on the xamarin bridge release?

Thanks!

**Comment by DoDoENT** [comment]
Not at the moment.

However, you can check how bridge can be created with our [BlinkID product](https://github.com/BlinkID/blinkid-xamarin). It has the same API as BlinkOCR, but has more features. You can use the BlinkID Xamarin bridge for testing and later you can create your own Xamarin bridge for BlinkOCR if you only need BlinkOCR, but not BlinkID features.
