### ISSUE TITLE
TEST ISSUE

### ISSUE THREAD

**Issue by culoi** [blinkinput/blinkinput-xamarin#2]
ANSWER GOES HERE

**Comment by MicroblinkTechSupport** [comment]
Answer 2

**Comment by culoi** [comment]
ANSWER 4 Github direct

**Comment by MicroblinkTechSupport** [comment]
Reply from mail

Ivan CuloLead Support Engineer
+385976240280
Microblink LTD
www.microblink.com <https://microblink.com/>
<https://microblink.com/>
<https://microblink.com/news-events/news/blinkid-web-api-is-now-live>NEW!
BlinkID Web API is now live.
Read more.
<https://microblink.com/news-events/news/blinkid-web-api-is-now-live>

**Comment by MicroblinkTechSupport** [comment]
Test from mobile

**Comment by MicroblinkTechSupport** [comment]
Test from web2
